version: '3.9'
services:
  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres:16.3
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 55432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  redis:
    container_name: redis
    hostname: redis
    image: redis:7.4-rc2
    restart: always
    ports:
      - 60379:6379
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata: